### ISSUE TITLE
Configure logging using k8s configmap

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#323]
Expose standard way of configuring logging via json and/or yaml. In essence we should support `Iogging.config.dictConfig`, and at deployment the user can provide the configuration content. 

Want to allow users to be able to define their own handlers and their respective log levels and document how/where. 

Also see [protari logging docs](https://docs.protari.d61.io/dev/setting-up/logging/).

**Comment by hardbyte** [comment]
Last thing required before closing this is configuration of logging in a k8s configmap.

**Comment by gusmith** [comment]
Will be closed by #448

**Comment by gusmith** [comment]
#448 merged in.
