### ISSUE TITLE
Migrate to open source CI tool/s

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#329]
Most likely candidate is travis-ci.org - need something that can build and test a docker microservice though.

Other options?

**Comment by hardbyte** [comment]
Looks like we can have a stage which builds docker images then stages which test/benchmark them.

https://docs.travis-ci.com/user/build-stages/share-docker-image/

**Comment by gusmith** [comment]
Is it redundant with #390 ?

**Comment by hardbyte** [comment]
Once we've removed appveyor (and ideally Jenkins) this can be closed. 

I'd also like to investigate the bots/plugins that projects use to allow PR testing after a project member okays it.

**Comment by gusmith** [comment]
Since v1.11.2, we stopped using Jenkins. And AppVeyor has been replaced by Azure Dev-Ops (#390 ).
