### ISSUE TITLE
Remove quay.io readonly secret

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#338]
As this repository was private we had deployment support for pulling from a private docker repository. The default docker registry secret used by k8s to pull the images (found [here](https://github.com/n1analytics/entity-service/blob/develop/deployment/n1-coreos-secret.yaml)) can now be removed. Note the token is scoped as read only to a public repository.

The templates should still support pulling from private container repositories, but a secret is not needed by default.

**Comment by gusmith** [comment]
With the PRs #388 and #392 , we will be able to remove every mention of quay.io as we will start using dockerhub, cf issue #367
