### ISSUE TITLE
Security issues in nginx container

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#378]
[Quay.io](https://quay.io/repository/n1analytics/entity-nginx/manifest/sha256:d07cc38a6edc72a20810a11a607d95ef8a902fff4276e7f3043eefb97fada597?tab=vulnerabilities)

![image](https://user-images.githubusercontent.com/855189/58754360-a6bf3d80-8511-11e9-874e-3d20fece9ef7.png)

**Comment by gusmith** [comment]
Release `1.4.2-develop` is passing quay.io tests.
[quay.io](https://quay.io/repository/n1analytics/entity-nginx/manifest/sha256:aa3fdde1ec492efa3ee81be0ab389c9c34f1587993339d5496e702ceec2a2fcf?tab=vulnerabilities)

**Comment by hardbyte** [comment]
Can be closed once released

**Comment by gusmith** [comment]
v1.4.2 has been released 2 months ago on dockerhub.
