### ISSUE TITLE
Delete run returning incorrect status code

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#417]
After merging #413 Azure's integration testing has found a way it can fail [1].

The delete run endpoint is pretty simple:

```python 
def delete(project_id, run_id):
    log = logger.bind(pid=project_id, rid=run_id)
    log.debug("request to delete run")
    authorize_run_detail(project_id, run_id)
    log.debug("approved request to delete run")

    with db.DBConn() as conn:
        log.debug("Retrieving run details from database")
        similarity_file = get_similarity_file_for_run(conn, run_id)
        if similarity_file:
            log.debug("Queuing task to remove similarities file from object store")
            delete_minio_objects.delay([similarity_file], project_id)
        delete_run_data(conn, run_id)

    log.debug("Deleted run")
    return '', 204
```

I'm not sure how a status 200 was returned, and Azure doesn't save the container logs which might have some clues as to what happened (I'll open an issue for that too).

1: https://dev.azure.com/data61/Anonlink/_build/results?buildId=334&view=logs&j=aac7439e-97d6-512d-3e06-b7446a540cac&t=87776385-7f7e-5153-98cd-b266f414aa22&l=42

**Comment by gusmith** [comment]
Is it related to https://github.com/data61/clkhash/pull/297?

**Comment by hardbyte** [comment]
Maybe an older deployment serviced the `DELETE` request which gave the old behavior of returning a `200` this could happen if the same ingress was accidentally used with two different backends.

Closing but will reopen if we see it again.
