### ISSUE TITLE
Use k8s python package instead of subprocess and sheel command in CI

### ISSUE THREAD

**Issue by gusmith** [data61/anonlink-entity-service#446]
In the steps during which we are copying the logs from the deployment containers after having run tests, we are currently using a shell command relying on `subprocess.run`.
Instead there is a python package https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#read_namespaced_pod_log which would enable the same functionality.

**Comment by hardbyte** [comment]
I've replaced that shell script with azure devops commands
