### ISSUE TITLE
tests `test_project_run_status` are currently useless (or redundant)

### ISSUE THREAD

**Issue by gusmith** [data61/anonlink-entity-service#457]
In dev, the tests in `test_project_run_status` are checking if the run is progressing "normally" (i.e. the stages are increasing, the relative progress is also increasing, etc).
But, they all call the method `wait_approx_run_time` which supposedly waits for the time to complete (if the number of clks computed per second is valid), *and* it waits for an extra 5 seconds (which I'm assuming was added because the CI was slow or something).

But each runs tested by this method takes around 1.5s on my machine, so by waiting 5 seconds, we are actually always checking that the run has completed. As the tests are running something like 16 times, we are adding a bit more than an extra minute to the tests for no relevant output as we are already testing these runs to completion.

@wilko77 mentioned that this may need to be integrated in the method `wait_for_run_completion` which could validate every time that the run is progressing. It would be quite nice :)

**Comment by hardbyte** [comment]
@wilko77 you had thought on this regarding removing the tests and adding asserts to all long running tests that ensure the messages are sent in the correct order and progress never goes down.
