### ISSUE TITLE
Deployment testing

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#87]
Need to have tests of the helm charts - can we get jenkins to deploy each PR and throw some tests at the deployment?

https://github.com/kubernetes/helm/blob/master/docs/chart_tests.md

**Comment by gusmith** [comment]
Should be closed by #392 : the integration tests are run in Azure pipeline instead of jenkins, the test results published in Azure, but not using `helm test`.

**Comment by gusmith** [comment]
Test results are back from Azure, logs are back too.
